//Exécuter le bloc suivant (entre les parenthèses) pour installer les Quarks nécessaires.
(
[ "ddwPatterns", "crucial-library", "ddwGUIEnhancements", "ddwStatusBox", "UnitTesting", "ddwCommon", "ddwMIDI", "ddwTemperament", "MathLib", "SenseWorld", "dmx", "PopUpTreeMenu", "TabbedView2_QT", "NetLib", "ddwVoicer", "KMeans", "ddwPrototype", "ddwPeakMonitor", "ddwMixerChannel", "ddwChucklib", "DayTimer", "XML", "Ctk", "wslib", "ddwEQ", "arduino", "FileLog", "crucialviews", "ddwSensitivity", "Debug", "dewdrop_lib", "Modality-toolkit", "AllGui", "Vowel", "Dirt-Samples", "SuperDirt", "lfsaw.de", "MeTA", "PushPull" ].do({|i| Quarks.install(i) });
)


